CREATE TABLE "MOSIP"."ECOWAS_MAP" ("COUNTRY_CODE" VARCHAR(36) NOT NULL);
ALTER TABLE "MOSIP"."ECOWAS_MAP" ADD CONSTRAINT "PK_ECOWAS_CODE" PRIMARY KEY ("COUNTRY_CODE");
INSERT INTO "MOSIP"."ECOWAS_MAP" VALUES ('India');
INSERT INTO "MOSIP"."ECOWAS_MAP" VALUES ('China');
INSERT INTO "MOSIP"."ECOWAS_MAP" VALUES ('America');