package io.mosip.packet.core.constant;

/**
 * 
 * @author Sowmya
 *
 */
public enum ApiName {
	DOCUMENT_CATEGORY,
	DOCUMENT_TYPES,
	LATEST_ID_SCHEMA,
	BIOSDK_QUALITY_CHECK,
	MASTER_VALIDATOR_SERVICE_NAME,
	GET_CERTIFICATE,
	PACKET_SYNC_V2,
	PACKET_SYNC,
	PACKET_UPLOAD,
	KERNEL_DECRYPT,
	BQAT_BIOSDK_QUALITY_CHECK

}
