package io.mosip.packet.core.constant;

import org.springframework.stereotype.Component;

import java.util.HashMap;

@Component
public class TableQueries {;
    private static HashMap<String, HashMap<DBTypes, String>> queryMap;

    public TableQueries() {
        HashMap<DBTypes, String> inserQuerytMap = new HashMap<>();
        inserQuerytMap.put(DBTypes.MYSQL, "INSERT INTO <TABLE_NAME> (SESSION_KEY, OFFSET_VALUE, IN_USE) VALUES ('<SESSION_ID>', '<VALUE>', '<IN_USE>') ON DUPLICATE KEY UPDATE SESSION_KEY = '<SESSION_ID>', OFFSET_VALUE = '<VALUE>', IN_USE = '<IN_USE>'");
        inserQuerytMap.put(DBTypes.POSTGRESQL, "INSERT INTO <TABLE_NAME> ( SESSION_KEY, OFFSET_VALUE, IN_USE ) VALUES ('<SESSION_ID>', '<VALUE>', '<IN_USE>') ON CONFLICT(SESSION_KEY) DO UPDATE SET SESSION_KEY = '<SESSION_ID>', OFFSET_VALUE = '<VALUE>', IN_USE = '<IN_USE>'");
        inserQuerytMap.put(DBTypes.ORACLE, "MERGE INTO <TABLE_NAME> T USING (SELECT 1 FROM DUAL) C ON (T.SESSION_KEY = '<SESSION_ID>') WHEN NOT MATCHED THEN INSERT (SESSION_KEY, OFFSET_VALUE, IN_USE) values('<SESSION_ID>', <VALUE>, '<IN_USE>') WHEN MATCHED THEN UPDATE SET OFFSET_VALUE = '<VALUE>', IN_USE = '<IN_USE>'");
        inserQuerytMap.put(DBTypes.MSSQL, "IF EXISTS (SELECT * FROM <TABLE_NAME> WHERE SESSION_KEY = '<SESSION_ID>') UPDATE <TABLE_NAME> SET SESSION_KEY = '<SESSION_ID>', OFFSET_VALUE = '<VALUE>', IN_USE = '<IN_USE>' WHERE SESSION_KEY = '<SESSION_ID>' ELSE INSERT INTO <TABLE_NAME> (SESSION_KEY, OFFSET_VALUE, IN_USE) VALUES('<SESSION_ID>', <VALUE>, '<IN_USE>')");

        HashMap<DBTypes, String> inserPacketTrackerQueryMap = new HashMap<>();
        inserPacketTrackerQueryMap.put(DBTypes.MYSQL, "INSERT INTO <TABLE_NAME> (REF_ID, REG_NO, STATUS, CR_BY, CR_DTIMES, SESSION_KEY, ACTIVITY, PROCESS, COMMENTS) VALUES ('<REF_ID>', '<REG_NO>', '<STATUS>', '<CR_BY>', '<CR_DTIMES>', '<SESSION_KEY>', '<ACTIVITY>', '<PROCESS>', '<COMMENTS>') ON DUPLICATE KEY UPDATE REF_ID = '<REF_ID>', REG_NO = '<REG_NO>', STATUS = '<STATUS>', CR_BY = '<CR_BY>', CR_DTIMES = '<CR_DTIMES>', SESSION_KEY = '<SESSION_KEY>', ACTIVITY = '<ACTIVITY>', PROCESS = '<PROCESS>', COMMENTS = '<COMMENTS>'");
        inserPacketTrackerQueryMap.put(DBTypes.POSTGRESQL, "INSERT INTO <TABLE_NAME> (REF_ID, REG_NO, STATUS, CR_BY, CR_DTIMES, SESSION_KEY, ACTIVITY, PROCESS, COMMENTS) VALUES ('<REF_ID>', '<REG_NO>', '<STATUS>', '<CR_BY>', '<CR_DTIMES>', '<SESSION_KEY>', '<ACTIVITY>', '<PROCESS>', '<COMMENTS>') ON CONFLICT(SESSION_KEY,REF_ID) DO UPDATE SET REF_ID = '<REF_ID>', REG_NO = '<REG_NO>', STATUS = '<STATUS>', CR_BY = '<CR_BY>', CR_DTIMES = '<CR_DTIMES>', SESSION_KEY = '<SESSION_KEY>', ACTIVITY = '<ACTIVITY>', PROCESS = '<PROCESS>', COMMENTS = '<COMMENTS>'");
        inserPacketTrackerQueryMap.put(DBTypes.ORACLE, "MERGE INTO <TABLE_NAME> T USING (SELECT 1 FROM DUAL) C ON (T.SESSION_KEY = '<SESSION_ID>' AND T.REF_ID = '<REF_ID>') WHEN NOT MATCHED THEN INSERT (REF_ID, REG_NO, STATUS, CR_BY, CR_DTIMES, SESSION_KEY, ACTIVITY, PROCESS, COMMENTS) values('<REF_ID>', '<REG_NO>', '<STATUS>', '<CR_BY>', '<CR_DTIMES>', '<SESSION_KEY>', '<ACTIVITY>', '<PROCESS>', '<COMMENTS>') WHEN MATCHED THEN UPDATE SET REG_NO = '<REG_NO>', STATUS = '<STATUS>', CR_BY = '<CR_BY>', CR_DTIMES = '<CR_DTIMES>', ACTIVITY = '<ACTIVITY>', PROCESS = '<PROCESS>', COMMENTS = '<COMMENTS>'");
        inserPacketTrackerQueryMap.put(DBTypes.MSSQL, "IF EXISTS (SELECT * FROM <TABLE_NAME> WHERE SESSION_KEY = '<SESSION_KEY>' AND REF_ID = '<REF_ID>') UPDATE <TABLE_NAME> SET REF_ID = '<REF_ID>', REG_NO = '<REG_NO>', STATUS = '<STATUS>', CR_BY = '<CR_BY>', CR_DTIMES = '<CR_DTIMES>', SESSION_KEY = '<SESSION_KEY>', ACTIVITY = '<ACTIVITY>', PROCESS = '<PROCESS>', COMMENTS = '<COMMENTS>' WHERE SESSION_KEY = '<SESSION_KEY>' AND REF_ID = '<REF_ID>' ELSE INSERT INTO <TABLE_NAME> (REF_ID, REG_NO, STATUS, CR_BY, CR_DTIMES, SESSION_KEY, ACTIVITY, PROCESS, COMMENTS) VALUES('<REF_ID>', '<REG_NO>', '<STATUS>', '<CR_BY>', '<CR_DTIMES>', '<SESSION_KEY>', '<ACTIVITY>', '<PROCESS>', '<COMMENTS>')");


        queryMap = new HashMap<>();
        queryMap.put(RegistrationConstants.OFFSET_TRACKER_TABLE_NAME, inserQuerytMap);
        queryMap.put(RegistrationConstants.TRACKER_TABLE_NAME, inserPacketTrackerQueryMap);
    }

    public static String getInsertQueries(String  tableName, DBTypes dbType) {
        return queryMap.get(tableName).get(dbType);
    }
}
