-- ============================

-- This file was created using Derby's dblook utility.
-- Timestamp: 2020-08-30 22:41:40.912
-- Source database is: db/reg
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for schemas
-- ----------------------------------------------

CREATE SCHEMA "MOSIP";

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "MOSIP"."LOCATION" ("CODE" VARCHAR(36) NOT NULL, "NAME" VARCHAR(128) NOT NULL, "HIERARCHY_LEVEL" SMALLINT NOT NULL, "HIERARCHY_LEVEL_NAME" VARCHAR(64) NOT NULL, "PARENT_LOC_CODE" VARCHAR(32), "LANG_CODE" VARCHAR(3) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);

CREATE TABLE "MOSIP"."DOC_CATEGORY" ("CODE" VARCHAR(36) NOT NULL, "NAME" VARCHAR(64) NOT NULL, "DESCR" VARCHAR(128), "LANG_CODE" VARCHAR(3) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);

CREATE TABLE "MOSIP"."MACHINE_SPEC" ("ID" VARCHAR(36) NOT NULL, "NAME" VARCHAR(64) NOT NULL, "BRAND" VARCHAR(32) NOT NULL, "MODEL" VARCHAR(16) NOT NULL, "MTYP_CODE" VARCHAR(36) NOT NULL, "MIN_DRIVER_VER" VARCHAR(16) NOT NULL, "DESCR" VARCHAR(256), "LANG_CODE" VARCHAR(3), "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);

CREATE TABLE "MOSIP"."DOC_TYPE" ("CODE" VARCHAR(36) NOT NULL, "NAME" VARCHAR(64) NOT NULL, "DESCR" VARCHAR(128), "LANG_CODE" VARCHAR(3) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);

CREATE TABLE "MOSIP"."BLOCKLISTED_WORDS" ("WORD" VARCHAR(128) NOT NULL, "DESCR" VARCHAR(256), "LANG_CODE" VARCHAR(3) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);

CREATE TABLE "MOSIP"."MACHINE_MASTER" ("ID" VARCHAR(10) NOT NULL, "NAME" VARCHAR(64) NOT NULL, "MAC_ADDRESS" VARCHAR(64), "SERIAL_NUM" VARCHAR(64), "IP_ADDRESS" VARCHAR(17), "PUBLIC_KEY" CLOB(2147483647) NOT NULL, "KEY_INDEX" VARCHAR(128) NOT NULL, "VALIDITY_END_DTIMES" TIMESTAMP, "MSPEC_ID" VARCHAR(36) NOT NULL, "LANG_CODE" VARCHAR(3), "IS_ACTIVE" BOOLEAN NOT NULL, "REG_CNTR_ID" VARCHAR(10) NOT NULL, "CR_BY" VARCHAR(256) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(256), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);

CREATE TABLE "MOSIP"."APPLICANT_VALID_DOCUMENT" ("APPTYP_CODE" VARCHAR(36) NOT NULL, "DOCCAT_CODE" VARCHAR(36) NOT NULL, "DOCTYP_CODE" VARCHAR(36) NOT NULL, "LANG_CODE" VARCHAR(3) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);

CREATE TABLE "MOSIP"."MACHINE_TYPE" ("CODE" VARCHAR(36) NOT NULL, "NAME" VARCHAR(64) NOT NULL, "DESCR" VARCHAR(128), "LANG_CODE" VARCHAR(3), "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);

ALTER TABLE "MOSIP"."DOC_CATEGORY" ADD CONSTRAINT "PK_DOCCAT_CODE" PRIMARY KEY ("CODE", "LANG_CODE");

ALTER TABLE "MOSIP"."MACHINE_MASTER" ADD CONSTRAINT "PK_MACHM_ID" PRIMARY KEY ("ID");

ALTER TABLE "MOSIP"."MACHINE_TYPE" ADD CONSTRAINT "PK_MTYP_CODE" PRIMARY KEY ("CODE");

ALTER TABLE "MOSIP"."MACHINE_SPEC" ADD CONSTRAINT "PK_MSPEC_CODE" PRIMARY KEY ("ID");

CREATE TABLE "MOSIP"."BLOCKLISTED_WORDS"  ADD CONSTRAINT "PK_BLW_CODE" PRIMARY KEY ("WORD");